// Code generated by otel-lint. DO NOT EDIT.
package metrics

import (
	"github.com/ymtdzzz/otel-lint/pkg/rule"
)

var RulesDeprecatedv1260 = []*rule.MetricRule{
	ruleDeprecatedDbClientConnectionsUsagev1260,
	ruleDeprecatedDbClientConnectionsIdleMaxv1260,
	ruleDeprecatedDbClientConnectionsIdleMinv1260,
	ruleDeprecatedDbClientConnectionsMaxv1260,
	ruleDeprecatedDbClientConnectionsPendingRequestsv1260,
	ruleDeprecatedDbClientConnectionsTimeoutsv1260,
	ruleDeprecatedDbClientConnectionsCreateTimev1260,
	ruleDeprecatedDbClientConnectionsWaitTimev1260,
	ruleDeprecatedDbClientConnectionsUseTimev1260,
}

var ruleDeprecatedDbClientConnectionsUsagev1260 = &rule.MetricRule{
	Name:         "deprecated.db.client.connections.usage",
	Title:        "Deprecated, use `db.client.connection.count` instead.",
	Check:        func(m *rule.Metrics) bool { return metricNameNot(m, "db.client.connections.usage") },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.26.0",
}

var ruleDeprecatedDbClientConnectionsIdleMaxv1260 = &rule.MetricRule{
	Name:         "deprecated.db.client.connections.idle.max",
	Title:        "Deprecated, use `db.client.connection.idle.max` instead.",
	Check:        func(m *rule.Metrics) bool { return metricNameNot(m, "db.client.connections.idle.max") },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.26.0",
}

var ruleDeprecatedDbClientConnectionsIdleMinv1260 = &rule.MetricRule{
	Name:         "deprecated.db.client.connections.idle.min",
	Title:        "Deprecated, use `db.client.connection.idle.min` instead.",
	Check:        func(m *rule.Metrics) bool { return metricNameNot(m, "db.client.connections.idle.min") },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.26.0",
}

var ruleDeprecatedDbClientConnectionsMaxv1260 = &rule.MetricRule{
	Name:         "deprecated.db.client.connections.max",
	Title:        "Deprecated, use `db.client.connection.max` instead.",
	Check:        func(m *rule.Metrics) bool { return metricNameNot(m, "db.client.connections.max") },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.26.0",
}

var ruleDeprecatedDbClientConnectionsPendingRequestsv1260 = &rule.MetricRule{
	Name:         "deprecated.db.client.connections.pending_requests",
	Title:        "Deprecated, use `db.client.connection.pending_requests` instead.",
	Check:        func(m *rule.Metrics) bool { return metricNameNot(m, "db.client.connections.pending_requests") },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.26.0",
}

var ruleDeprecatedDbClientConnectionsTimeoutsv1260 = &rule.MetricRule{
	Name:         "deprecated.db.client.connections.timeouts",
	Title:        "Deprecated, use `db.client.connection.timeouts` instead.",
	Check:        func(m *rule.Metrics) bool { return metricNameNot(m, "db.client.connections.timeouts") },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.26.0",
}

var ruleDeprecatedDbClientConnectionsCreateTimev1260 = &rule.MetricRule{
	Name:         "deprecated.db.client.connections.create_time",
	Title:        "Deprecated, use `db.client.connection.create_time` instead. Note: the unit also changed from `ms` to `s`.",
	Check:        func(m *rule.Metrics) bool { return metricNameNot(m, "db.client.connections.create_time") },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.26.0",
}

var ruleDeprecatedDbClientConnectionsWaitTimev1260 = &rule.MetricRule{
	Name:         "deprecated.db.client.connections.wait_time",
	Title:        "Deprecated, use `db.client.connection.wait_time` instead. Note: the unit also changed from `ms` to `s`.",
	Check:        func(m *rule.Metrics) bool { return metricNameNot(m, "db.client.connections.wait_time") },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.26.0",
}

var ruleDeprecatedDbClientConnectionsUseTimev1260 = &rule.MetricRule{
	Name:         "deprecated.db.client.connections.use_time",
	Title:        "Deprecated, use `db.client.connection.use_time` instead. Note: the unit also changed from `ms` to `s`.",
	Check:        func(m *rule.Metrics) bool { return metricNameNot(m, "db.client.connections.use_time") },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.26.0",
}

