// Code generated by otel-lint. DO NOT EDIT.
package attributes

import (
	"github.com/ymtdzzz/otel-lint/pkg/rule"
)

var RulesDeprecatedv1260 = []*rule.AttributeRule{
	ruleDeprecatedContainerLabelsv1260,
	ruleDeprecatedDbCassandraTablev1260,
	ruleDeprecatedDbConnectionStringv1260,
	ruleDeprecatedDbCosmosdbContainerv1260,
	ruleDeprecatedDbInstanceIdv1260,
	ruleDeprecatedDbJdbcDriverClassnamev1260,
	ruleDeprecatedDbMongodbCollectionv1260,
	ruleDeprecatedDbMssqlInstanceNamev1260,
	ruleDeprecatedDbNamev1260,
	ruleDeprecatedDbOperationv1260,
	ruleDeprecatedDbRedisDatabaseIndexv1260,
	ruleDeprecatedDbSqlTablev1260,
	ruleDeprecatedDbStatementv1260,
	ruleDeprecatedDbUserv1260,
	ruleDeprecatedHttpClientIpv1260,
	ruleDeprecatedHttpFlavorv1260,
	ruleDeprecatedHttpHostv1260,
	ruleDeprecatedHttpMethodv1260,
	ruleDeprecatedHttpRequestContentLengthv1260,
	ruleDeprecatedHttpRequestContentLengthUncompressedv1260,
	ruleDeprecatedHttpResponseContentLengthv1260,
	ruleDeprecatedHttpResponseContentLengthUncompressedv1260,
	ruleDeprecatedHttpSchemev1260,
	ruleDeprecatedHttpServerNamev1260,
	ruleDeprecatedHttpStatusCodev1260,
	ruleDeprecatedHttpTargetv1260,
	ruleDeprecatedHttpUrlv1260,
	ruleDeprecatedHttpUserAgentv1260,
	ruleDeprecatedIosStatev1260,
	ruleDeprecatedK8SPodLabelsv1260,
	ruleDeprecatedMessageCompressedSizev1260,
	ruleDeprecatedMessageIdv1260,
	ruleDeprecatedMessageTypev1260,
	ruleDeprecatedMessageUncompressedSizev1260,
	ruleDeprecatedMessagingClientIdv1260,
	ruleDeprecatedMessagingKafkaDestinationPartitionv1260,
	ruleDeprecatedMessagingOperationv1260,
	ruleDeprecatedNetHostIpv1260,
	ruleDeprecatedNetHostNamev1260,
	ruleDeprecatedNetHostPortv1260,
	ruleDeprecatedNetPeerIpv1260,
	ruleDeprecatedNetPeerNamev1260,
	ruleDeprecatedNetPeerPortv1260,
	ruleDeprecatedNetProtocolNamev1260,
	ruleDeprecatedNetProtocolVersionv1260,
	ruleDeprecatedNetSockFamilyv1260,
	ruleDeprecatedNetSockHostAddrv1260,
	ruleDeprecatedNetSockHostPortv1260,
	ruleDeprecatedNetSockPeerAddrv1260,
	ruleDeprecatedNetSockPeerNamev1260,
	ruleDeprecatedNetSockPeerPortv1260,
	ruleDeprecatedNetTransportv1260,
	ruleDeprecatedOtelLibraryNamev1260,
	ruleDeprecatedOtelLibraryVersionv1260,
	ruleDeprecatedPoolNamev1260,
	ruleDeprecatedStatev1260,
	ruleDeprecatedSystemProcessesStatusv1260,
}

var ruleDeprecatedContainerLabelsv1260 = &rule.AttributeRule{
	Name:         "deprecated.container.labels",
	Title:        "Deprecated, use `container.label` instead.",
	Check:        checkDeprecatedContainerLabelsv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedContainerLabelsv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("container.labels")
}

var ruleDeprecatedDbCassandraTablev1260 = &rule.AttributeRule{
	Name:         "deprecated.db.cassandra.table",
	Title:        "Deprecated, use `db.collection.name` instead.",
	Check:        checkDeprecatedDbCassandraTablev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbCassandraTablev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.cassandra.table")
}

var ruleDeprecatedDbConnectionStringv1260 = &rule.AttributeRule{
	Name:         "deprecated.db.connection_string",
	Title:        "Deprecated, use `server.address`, `server.port` attributes instead.",
	Check:        checkDeprecatedDbConnectionStringv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbConnectionStringv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.connection_string")
}

var ruleDeprecatedDbCosmosdbContainerv1260 = &rule.AttributeRule{
	Name:         "deprecated.db.cosmosdb.container",
	Title:        "Deprecated, use `db.collection.name` instead.",
	Check:        checkDeprecatedDbCosmosdbContainerv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbCosmosdbContainerv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.cosmosdb.container")
}

var ruleDeprecatedDbInstanceIdv1260 = &rule.AttributeRule{
	Name:         "deprecated.db.instance.id",
	Title:        "Deprecated, no general replacement at this time. For Elasticsearch, use `db.elasticsearch.node.name` instead.",
	Check:        checkDeprecatedDbInstanceIdv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbInstanceIdv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.instance.id")
}

var ruleDeprecatedDbJdbcDriverClassnamev1260 = &rule.AttributeRule{
	Name:         "deprecated.db.jdbc.driver_classname",
	Title:        "Removed, no replacement at this time.",
	Check:        checkDeprecatedDbJdbcDriverClassnamev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbJdbcDriverClassnamev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.jdbc.driver_classname")
}

var ruleDeprecatedDbMongodbCollectionv1260 = &rule.AttributeRule{
	Name:         "deprecated.db.mongodb.collection",
	Title:        "Deprecated, use `db.collection.name` instead.",
	Check:        checkDeprecatedDbMongodbCollectionv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbMongodbCollectionv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.mongodb.collection")
}

var ruleDeprecatedDbMssqlInstanceNamev1260 = &rule.AttributeRule{
	Name:         "deprecated.db.mssql.instance_name",
	Title:        "Deprecated, SQL Server instance is now populated as a part of `db.namespace` attribute.",
	Check:        checkDeprecatedDbMssqlInstanceNamev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbMssqlInstanceNamev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.mssql.instance_name")
}

var ruleDeprecatedDbNamev1260 = &rule.AttributeRule{
	Name:         "deprecated.db.name",
	Title:        "Deprecated, use `db.namespace` instead.",
	Check:        checkDeprecatedDbNamev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbNamev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.name")
}

var ruleDeprecatedDbOperationv1260 = &rule.AttributeRule{
	Name:         "deprecated.db.operation",
	Title:        "Deprecated, use `db.operation.name` instead.",
	Check:        checkDeprecatedDbOperationv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbOperationv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.operation")
}

var ruleDeprecatedDbRedisDatabaseIndexv1260 = &rule.AttributeRule{
	Name:         "deprecated.db.redis.database_index",
	Title:        "Deprecated, use `db.namespace` instead.",
	Check:        checkDeprecatedDbRedisDatabaseIndexv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbRedisDatabaseIndexv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.redis.database_index")
}

var ruleDeprecatedDbSqlTablev1260 = &rule.AttributeRule{
	Name:         "deprecated.db.sql.table",
	Title:        "Deprecated, use `db.collection.name` instead.",
	Check:        checkDeprecatedDbSqlTablev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbSqlTablev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.sql.table")
}

var ruleDeprecatedDbStatementv1260 = &rule.AttributeRule{
	Name:         "deprecated.db.statement",
	Title:        "The database statement being executed.",
	Check:        checkDeprecatedDbStatementv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbStatementv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.statement")
}

var ruleDeprecatedDbUserv1260 = &rule.AttributeRule{
	Name:         "deprecated.db.user",
	Title:        "Deprecated, no replacement at this time.",
	Check:        checkDeprecatedDbUserv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbUserv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.user")
}

var ruleDeprecatedHttpClientIpv1260 = &rule.AttributeRule{
	Name:         "deprecated.http.client_ip",
	Title:        "Deprecated, use `client.address` instead.",
	Check:        checkDeprecatedHttpClientIpv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpClientIpv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.client_ip")
}

var ruleDeprecatedHttpFlavorv1260 = &rule.AttributeRule{
	Name:         "deprecated.http.flavor",
	Title:        "Deprecated, use `network.protocol.name` instead.",
	Check:        checkDeprecatedHttpFlavorv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpFlavorv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.flavor")
}

var ruleDeprecatedHttpHostv1260 = &rule.AttributeRule{
	Name:         "deprecated.http.host",
	Title:        "Deprecated, use one of `server.address`, `client.address` or `http.request.header.host` instead, depending on the usage.",
	Check:        checkDeprecatedHttpHostv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpHostv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.host")
}

var ruleDeprecatedHttpMethodv1260 = &rule.AttributeRule{
	Name:         "deprecated.http.method",
	Title:        "Deprecated, use `http.request.method` instead.",
	Check:        checkDeprecatedHttpMethodv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpMethodv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.method")
}

var ruleDeprecatedHttpRequestContentLengthv1260 = &rule.AttributeRule{
	Name:         "deprecated.http.request_content_length",
	Title:        "Deprecated, use `http.request.header.content-length` instead.",
	Check:        checkDeprecatedHttpRequestContentLengthv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpRequestContentLengthv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.request_content_length")
}

var ruleDeprecatedHttpRequestContentLengthUncompressedv1260 = &rule.AttributeRule{
	Name:         "deprecated.http.request_content_length_uncompressed",
	Title:        "Deprecated, use `http.request.body.size` instead.",
	Check:        checkDeprecatedHttpRequestContentLengthUncompressedv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpRequestContentLengthUncompressedv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.request_content_length_uncompressed")
}

var ruleDeprecatedHttpResponseContentLengthv1260 = &rule.AttributeRule{
	Name:         "deprecated.http.response_content_length",
	Title:        "Deprecated, use `http.response.header.content-length` instead.",
	Check:        checkDeprecatedHttpResponseContentLengthv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpResponseContentLengthv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.response_content_length")
}

var ruleDeprecatedHttpResponseContentLengthUncompressedv1260 = &rule.AttributeRule{
	Name:         "deprecated.http.response_content_length_uncompressed",
	Title:        "Deprecated, use `http.response.body.size` instead.",
	Check:        checkDeprecatedHttpResponseContentLengthUncompressedv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpResponseContentLengthUncompressedv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.response_content_length_uncompressed")
}

var ruleDeprecatedHttpSchemev1260 = &rule.AttributeRule{
	Name:         "deprecated.http.scheme",
	Title:        "Deprecated, use `url.scheme` instead.",
	Check:        checkDeprecatedHttpSchemev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpSchemev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.scheme")
}

var ruleDeprecatedHttpServerNamev1260 = &rule.AttributeRule{
	Name:         "deprecated.http.server_name",
	Title:        "Deprecated, use `server.address` instead.",
	Check:        checkDeprecatedHttpServerNamev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpServerNamev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.server_name")
}

var ruleDeprecatedHttpStatusCodev1260 = &rule.AttributeRule{
	Name:         "deprecated.http.status_code",
	Title:        "Deprecated, use `http.response.status_code` instead.",
	Check:        checkDeprecatedHttpStatusCodev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpStatusCodev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.status_code")
}

var ruleDeprecatedHttpTargetv1260 = &rule.AttributeRule{
	Name:         "deprecated.http.target",
	Title:        "Deprecated, use `url.path` and `url.query` instead.",
	Check:        checkDeprecatedHttpTargetv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpTargetv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.target")
}

var ruleDeprecatedHttpUrlv1260 = &rule.AttributeRule{
	Name:         "deprecated.http.url",
	Title:        "Deprecated, use `url.full` instead.",
	Check:        checkDeprecatedHttpUrlv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpUrlv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.url")
}

var ruleDeprecatedHttpUserAgentv1260 = &rule.AttributeRule{
	Name:         "deprecated.http.user_agent",
	Title:        "Deprecated, use `user_agent.original` instead.",
	Check:        checkDeprecatedHttpUserAgentv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpUserAgentv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.user_agent")
}

var ruleDeprecatedIosStatev1260 = &rule.AttributeRule{
	Name:         "deprecated.ios.state",
	Title:        "Deprecated use the `device.app.lifecycle` event definition including `ios.state` as a payload field instead.",
	Check:        checkDeprecatedIosStatev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedIosStatev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("ios.state")
}

var ruleDeprecatedK8SPodLabelsv1260 = &rule.AttributeRule{
	Name:         "deprecated.k8s.pod.labels",
	Title:        "Deprecated, use `k8s.pod.label` instead.",
	Check:        checkDeprecatedK8SPodLabelsv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedK8SPodLabelsv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("k8s.pod.labels")
}

var ruleDeprecatedMessageCompressedSizev1260 = &rule.AttributeRule{
	Name:         "deprecated.message.compressed_size",
	Title:        "Deprecated, use `rpc.message.compressed_size` instead.",
	Check:        checkDeprecatedMessageCompressedSizev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedMessageCompressedSizev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("message.compressed_size")
}

var ruleDeprecatedMessageIdv1260 = &rule.AttributeRule{
	Name:         "deprecated.message.id",
	Title:        "Deprecated, use `rpc.message.id` instead.",
	Check:        checkDeprecatedMessageIdv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedMessageIdv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("message.id")
}

var ruleDeprecatedMessageTypev1260 = &rule.AttributeRule{
	Name:         "deprecated.message.type",
	Title:        "Deprecated, use `rpc.message.type` instead.",
	Check:        checkDeprecatedMessageTypev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedMessageTypev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("message.type")
}

var ruleDeprecatedMessageUncompressedSizev1260 = &rule.AttributeRule{
	Name:         "deprecated.message.uncompressed_size",
	Title:        "Deprecated, use `rpc.message.uncompressed_size` instead.",
	Check:        checkDeprecatedMessageUncompressedSizev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedMessageUncompressedSizev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("message.uncompressed_size")
}

var ruleDeprecatedMessagingClientIdv1260 = &rule.AttributeRule{
	Name:         "deprecated.messaging.client_id",
	Title:        "Deprecated, use `messaging.client.id` instead.",
	Check:        checkDeprecatedMessagingClientIdv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedMessagingClientIdv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("messaging.client_id")
}

var ruleDeprecatedMessagingKafkaDestinationPartitionv1260 = &rule.AttributeRule{
	Name:         "deprecated.messaging.kafka.destination.partition",
	Title:        "Deprecated, use `messaging.destination.partition.id` instead.",
	Check:        checkDeprecatedMessagingKafkaDestinationPartitionv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedMessagingKafkaDestinationPartitionv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("messaging.kafka.destination.partition")
}

var ruleDeprecatedMessagingOperationv1260 = &rule.AttributeRule{
	Name:         "deprecated.messaging.operation",
	Title:        "Deprecated, use `messaging.operation.type` instead.",
	Check:        checkDeprecatedMessagingOperationv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedMessagingOperationv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("messaging.operation")
}

var ruleDeprecatedNetHostIpv1260 = &rule.AttributeRule{
	Name:         "deprecated.net.host.ip",
	Title:        "Deprecated, use `network.local.address`.",
	Check:        checkDeprecatedNetHostIpv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetHostIpv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.host.ip")
}

var ruleDeprecatedNetHostNamev1260 = &rule.AttributeRule{
	Name:         "deprecated.net.host.name",
	Title:        "Deprecated, use `server.address`.",
	Check:        checkDeprecatedNetHostNamev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetHostNamev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.host.name")
}

var ruleDeprecatedNetHostPortv1260 = &rule.AttributeRule{
	Name:         "deprecated.net.host.port",
	Title:        "Deprecated, use `server.port`.",
	Check:        checkDeprecatedNetHostPortv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetHostPortv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.host.port")
}

var ruleDeprecatedNetPeerIpv1260 = &rule.AttributeRule{
	Name:         "deprecated.net.peer.ip",
	Title:        "Deprecated, use `network.peer.address`.",
	Check:        checkDeprecatedNetPeerIpv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetPeerIpv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.peer.ip")
}

var ruleDeprecatedNetPeerNamev1260 = &rule.AttributeRule{
	Name:         "deprecated.net.peer.name",
	Title:        "Deprecated, use `server.address` on client spans and `client.address` on server spans.",
	Check:        checkDeprecatedNetPeerNamev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetPeerNamev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.peer.name")
}

var ruleDeprecatedNetPeerPortv1260 = &rule.AttributeRule{
	Name:         "deprecated.net.peer.port",
	Title:        "Deprecated, use `server.port` on client spans and `client.port` on server spans.",
	Check:        checkDeprecatedNetPeerPortv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetPeerPortv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.peer.port")
}

var ruleDeprecatedNetProtocolNamev1260 = &rule.AttributeRule{
	Name:         "deprecated.net.protocol.name",
	Title:        "Deprecated, use `network.protocol.name`.",
	Check:        checkDeprecatedNetProtocolNamev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetProtocolNamev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.protocol.name")
}

var ruleDeprecatedNetProtocolVersionv1260 = &rule.AttributeRule{
	Name:         "deprecated.net.protocol.version",
	Title:        "Deprecated, use `network.protocol.version`.",
	Check:        checkDeprecatedNetProtocolVersionv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetProtocolVersionv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.protocol.version")
}

var ruleDeprecatedNetSockFamilyv1260 = &rule.AttributeRule{
	Name:         "deprecated.net.sock.family",
	Title:        "Deprecated, use `network.transport` and `network.type`.",
	Check:        checkDeprecatedNetSockFamilyv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetSockFamilyv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.sock.family")
}

var ruleDeprecatedNetSockHostAddrv1260 = &rule.AttributeRule{
	Name:         "deprecated.net.sock.host.addr",
	Title:        "Deprecated, use `network.local.address`.",
	Check:        checkDeprecatedNetSockHostAddrv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetSockHostAddrv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.sock.host.addr")
}

var ruleDeprecatedNetSockHostPortv1260 = &rule.AttributeRule{
	Name:         "deprecated.net.sock.host.port",
	Title:        "Deprecated, use `network.local.port`.",
	Check:        checkDeprecatedNetSockHostPortv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetSockHostPortv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.sock.host.port")
}

var ruleDeprecatedNetSockPeerAddrv1260 = &rule.AttributeRule{
	Name:         "deprecated.net.sock.peer.addr",
	Title:        "Deprecated, use `network.peer.address`.",
	Check:        checkDeprecatedNetSockPeerAddrv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetSockPeerAddrv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.sock.peer.addr")
}

var ruleDeprecatedNetSockPeerNamev1260 = &rule.AttributeRule{
	Name:         "deprecated.net.sock.peer.name",
	Title:        "Deprecated, no replacement at this time.",
	Check:        checkDeprecatedNetSockPeerNamev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetSockPeerNamev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.sock.peer.name")
}

var ruleDeprecatedNetSockPeerPortv1260 = &rule.AttributeRule{
	Name:         "deprecated.net.sock.peer.port",
	Title:        "Deprecated, use `network.peer.port`.",
	Check:        checkDeprecatedNetSockPeerPortv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetSockPeerPortv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.sock.peer.port")
}

var ruleDeprecatedNetTransportv1260 = &rule.AttributeRule{
	Name:         "deprecated.net.transport",
	Title:        "Deprecated, use `network.transport`.",
	Check:        checkDeprecatedNetTransportv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetTransportv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.transport")
}

var ruleDeprecatedOtelLibraryNamev1260 = &rule.AttributeRule{
	Name:         "deprecated.otel.library.name",
	Title:        "",
	Check:        checkDeprecatedOtelLibraryNamev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedOtelLibraryNamev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("otel.library.name")
}

var ruleDeprecatedOtelLibraryVersionv1260 = &rule.AttributeRule{
	Name:         "deprecated.otel.library.version",
	Title:        "",
	Check:        checkDeprecatedOtelLibraryVersionv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedOtelLibraryVersionv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("otel.library.version")
}

var ruleDeprecatedPoolNamev1260 = &rule.AttributeRule{
	Name:         "deprecated.pool.name",
	Title:        "Deprecated, use `db.client.connections.pool.name` instead.",
	Check:        checkDeprecatedPoolNamev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedPoolNamev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("pool.name")
}

var ruleDeprecatedStatev1260 = &rule.AttributeRule{
	Name:         "deprecated.state",
	Title:        "Deprecated, use `db.client.connections.state` instead.",
	Check:        checkDeprecatedStatev1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedStatev1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("state")
}

var ruleDeprecatedSystemProcessesStatusv1260 = &rule.AttributeRule{
	Name:         "deprecated.system.processes.status",
	Title:        "Deprecated, use `system.process.status` instead.",
	Check:        checkDeprecatedSystemProcessesStatusv1260,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedSystemProcessesStatusv1260(a *rule.SignalAttributes) bool {
	return !a.KeyExists("system.processes.status")
}

