// Code generated by otel-lint. DO NOT EDIT.
package attributes

import (
	"github.com/ymtdzzz/otel-lint/pkg/rule"
)

var RulesDeprecatedv1250 = []*rule.AttributeRule{
	ruleDeprecatedContainerLabelsv1250,
	ruleDeprecatedDbConnectionStringv1250,
	ruleDeprecatedDbElasticsearchNodeNamev1250,
	ruleDeprecatedDbJdbcDriverClassnamev1250,
	ruleDeprecatedHttpFlavorv1250,
	ruleDeprecatedHttpMethodv1250,
	ruleDeprecatedHttpRequestContentLengthv1250,
	ruleDeprecatedHttpResponseContentLengthv1250,
	ruleDeprecatedHttpSchemev1250,
	ruleDeprecatedHttpStatusCodev1250,
	ruleDeprecatedHttpTargetv1250,
	ruleDeprecatedHttpUrlv1250,
	ruleDeprecatedHttpUserAgentv1250,
	ruleDeprecatedK8SPodLabelsv1250,
	ruleDeprecatedMessagingKafkaDestinationPartitionv1250,
	ruleDeprecatedNetHostNamev1250,
	ruleDeprecatedNetHostPortv1250,
	ruleDeprecatedNetPeerNamev1250,
	ruleDeprecatedNetPeerPortv1250,
	ruleDeprecatedNetProtocolNamev1250,
	ruleDeprecatedNetProtocolVersionv1250,
	ruleDeprecatedNetSockFamilyv1250,
	ruleDeprecatedNetSockHostAddrv1250,
	ruleDeprecatedNetSockHostPortv1250,
	ruleDeprecatedNetSockPeerAddrv1250,
	ruleDeprecatedNetSockPeerNamev1250,
	ruleDeprecatedNetSockPeerPortv1250,
	ruleDeprecatedNetTransportv1250,
	ruleDeprecatedOtelLibraryNamev1250,
	ruleDeprecatedOtelLibraryVersionv1250,
	ruleDeprecatedSystemProcessesStatusv1250,
}

var ruleDeprecatedContainerLabelsv1250 = &rule.AttributeRule{
	Name:         "deprecated.container.labels",
	Title:        "Deprecated, use `container.label` instead.",
	Check:        checkDeprecatedContainerLabelsv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedContainerLabelsv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("container.labels")
}

var ruleDeprecatedDbConnectionStringv1250 = &rule.AttributeRule{
	Name:         "deprecated.db.connection_string",
	Title:        "Deprecated, use `server.address`, `server.port` attributes instead.",
	Check:        checkDeprecatedDbConnectionStringv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbConnectionStringv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.connection_string")
}

var ruleDeprecatedDbElasticsearchNodeNamev1250 = &rule.AttributeRule{
	Name:         "deprecated.db.elasticsearch.node.name",
	Title:        "Deprecated, use `db.instance.id` instead.",
	Check:        checkDeprecatedDbElasticsearchNodeNamev1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbElasticsearchNodeNamev1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.elasticsearch.node.name")
}

var ruleDeprecatedDbJdbcDriverClassnamev1250 = &rule.AttributeRule{
	Name:         "deprecated.db.jdbc.driver_classname",
	Title:        "Removed, no replacement at this time.",
	Check:        checkDeprecatedDbJdbcDriverClassnamev1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedDbJdbcDriverClassnamev1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("db.jdbc.driver_classname")
}

var ruleDeprecatedHttpFlavorv1250 = &rule.AttributeRule{
	Name:         "deprecated.http.flavor",
	Title:        "Deprecated, use `network.protocol.name` instead.",
	Check:        checkDeprecatedHttpFlavorv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpFlavorv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.flavor")
}

var ruleDeprecatedHttpMethodv1250 = &rule.AttributeRule{
	Name:         "deprecated.http.method",
	Title:        "Deprecated, use `http.request.method` instead.",
	Check:        checkDeprecatedHttpMethodv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpMethodv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.method")
}

var ruleDeprecatedHttpRequestContentLengthv1250 = &rule.AttributeRule{
	Name:         "deprecated.http.request_content_length",
	Title:        "Deprecated, use `http.request.header.content-length` instead.",
	Check:        checkDeprecatedHttpRequestContentLengthv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpRequestContentLengthv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.request_content_length")
}

var ruleDeprecatedHttpResponseContentLengthv1250 = &rule.AttributeRule{
	Name:         "deprecated.http.response_content_length",
	Title:        "Deprecated, use `http.response.header.content-length` instead.",
	Check:        checkDeprecatedHttpResponseContentLengthv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpResponseContentLengthv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.response_content_length")
}

var ruleDeprecatedHttpSchemev1250 = &rule.AttributeRule{
	Name:         "deprecated.http.scheme",
	Title:        "Deprecated, use `url.scheme` instead.",
	Check:        checkDeprecatedHttpSchemev1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpSchemev1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.scheme")
}

var ruleDeprecatedHttpStatusCodev1250 = &rule.AttributeRule{
	Name:         "deprecated.http.status_code",
	Title:        "Deprecated, use `http.response.status_code` instead.",
	Check:        checkDeprecatedHttpStatusCodev1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpStatusCodev1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.status_code")
}

var ruleDeprecatedHttpTargetv1250 = &rule.AttributeRule{
	Name:         "deprecated.http.target",
	Title:        "Deprecated, use `url.path` and `url.query` instead.",
	Check:        checkDeprecatedHttpTargetv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpTargetv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.target")
}

var ruleDeprecatedHttpUrlv1250 = &rule.AttributeRule{
	Name:         "deprecated.http.url",
	Title:        "Deprecated, use `url.full` instead.",
	Check:        checkDeprecatedHttpUrlv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpUrlv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.url")
}

var ruleDeprecatedHttpUserAgentv1250 = &rule.AttributeRule{
	Name:         "deprecated.http.user_agent",
	Title:        "Deprecated, use `user_agent.original` instead.",
	Check:        checkDeprecatedHttpUserAgentv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedHttpUserAgentv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("http.user_agent")
}

var ruleDeprecatedK8SPodLabelsv1250 = &rule.AttributeRule{
	Name:         "deprecated.k8s.pod.labels",
	Title:        "Deprecated, use `k8s.pod.label` instead.",
	Check:        checkDeprecatedK8SPodLabelsv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedK8SPodLabelsv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("k8s.pod.labels")
}

var ruleDeprecatedMessagingKafkaDestinationPartitionv1250 = &rule.AttributeRule{
	Name:         "deprecated.messaging.kafka.destination.partition",
	Title:        "Deprecated, use `messaging.destination.partition.id` instead.",
	Check:        checkDeprecatedMessagingKafkaDestinationPartitionv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedMessagingKafkaDestinationPartitionv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("messaging.kafka.destination.partition")
}

var ruleDeprecatedNetHostNamev1250 = &rule.AttributeRule{
	Name:         "deprecated.net.host.name",
	Title:        "Deprecated, use `server.address`.",
	Check:        checkDeprecatedNetHostNamev1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetHostNamev1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.host.name")
}

var ruleDeprecatedNetHostPortv1250 = &rule.AttributeRule{
	Name:         "deprecated.net.host.port",
	Title:        "Deprecated, use `server.port`.",
	Check:        checkDeprecatedNetHostPortv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetHostPortv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.host.port")
}

var ruleDeprecatedNetPeerNamev1250 = &rule.AttributeRule{
	Name:         "deprecated.net.peer.name",
	Title:        "Deprecated, use `server.address` on client spans and `client.address` on server spans.",
	Check:        checkDeprecatedNetPeerNamev1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetPeerNamev1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.peer.name")
}

var ruleDeprecatedNetPeerPortv1250 = &rule.AttributeRule{
	Name:         "deprecated.net.peer.port",
	Title:        "Deprecated, use `server.port` on client spans and `client.port` on server spans.",
	Check:        checkDeprecatedNetPeerPortv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetPeerPortv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.peer.port")
}

var ruleDeprecatedNetProtocolNamev1250 = &rule.AttributeRule{
	Name:         "deprecated.net.protocol.name",
	Title:        "Deprecated, use `network.protocol.name`.",
	Check:        checkDeprecatedNetProtocolNamev1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetProtocolNamev1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.protocol.name")
}

var ruleDeprecatedNetProtocolVersionv1250 = &rule.AttributeRule{
	Name:         "deprecated.net.protocol.version",
	Title:        "Deprecated, use `network.protocol.version`.",
	Check:        checkDeprecatedNetProtocolVersionv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetProtocolVersionv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.protocol.version")
}

var ruleDeprecatedNetSockFamilyv1250 = &rule.AttributeRule{
	Name:         "deprecated.net.sock.family",
	Title:        "Deprecated, use `network.transport` and `network.type`.",
	Check:        checkDeprecatedNetSockFamilyv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetSockFamilyv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.sock.family")
}

var ruleDeprecatedNetSockHostAddrv1250 = &rule.AttributeRule{
	Name:         "deprecated.net.sock.host.addr",
	Title:        "Deprecated, use `network.local.address`.",
	Check:        checkDeprecatedNetSockHostAddrv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetSockHostAddrv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.sock.host.addr")
}

var ruleDeprecatedNetSockHostPortv1250 = &rule.AttributeRule{
	Name:         "deprecated.net.sock.host.port",
	Title:        "Deprecated, use `network.local.port`.",
	Check:        checkDeprecatedNetSockHostPortv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetSockHostPortv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.sock.host.port")
}

var ruleDeprecatedNetSockPeerAddrv1250 = &rule.AttributeRule{
	Name:         "deprecated.net.sock.peer.addr",
	Title:        "Deprecated, use `network.peer.address`.",
	Check:        checkDeprecatedNetSockPeerAddrv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetSockPeerAddrv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.sock.peer.addr")
}

var ruleDeprecatedNetSockPeerNamev1250 = &rule.AttributeRule{
	Name:         "deprecated.net.sock.peer.name",
	Title:        "Deprecated, no replacement at this time.",
	Check:        checkDeprecatedNetSockPeerNamev1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetSockPeerNamev1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.sock.peer.name")
}

var ruleDeprecatedNetSockPeerPortv1250 = &rule.AttributeRule{
	Name:         "deprecated.net.sock.peer.port",
	Title:        "Deprecated, use `network.peer.port`.",
	Check:        checkDeprecatedNetSockPeerPortv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetSockPeerPortv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.sock.peer.port")
}

var ruleDeprecatedNetTransportv1250 = &rule.AttributeRule{
	Name:         "deprecated.net.transport",
	Title:        "Deprecated, use `network.transport`.",
	Check:        checkDeprecatedNetTransportv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedNetTransportv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("net.transport")
}

var ruleDeprecatedOtelLibraryNamev1250 = &rule.AttributeRule{
	Name:         "deprecated.otel.library.name",
	Title:        "",
	Check:        checkDeprecatedOtelLibraryNamev1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedOtelLibraryNamev1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("otel.library.name")
}

var ruleDeprecatedOtelLibraryVersionv1250 = &rule.AttributeRule{
	Name:         "deprecated.otel.library.version",
	Title:        "",
	Check:        checkDeprecatedOtelLibraryVersionv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedOtelLibraryVersionv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("otel.library.version")
}

var ruleDeprecatedSystemProcessesStatusv1250 = &rule.AttributeRule{
	Name:         "deprecated.system.processes.status",
	Title:        "Deprecated, use `system.process.status` instead.",
	Check:        checkDeprecatedSystemProcessesStatusv1250,
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
}

func checkDeprecatedSystemProcessesStatusv1250(a *rule.SignalAttributes) bool {
	return !a.KeyExists("system.processes.status")
}

