// Code generated by otel-lint. DO NOT EDIT.
package attributes

import (
	"github.com/ymtdzzz/otel-lint/pkg/rule"
)

var RulesEnumv1250 = []*rule.AttributeRule{
	ruleEnumAndroidStatev1250,
	ruleEnumAwsEcsLaunchtypev1250,
	ruleEnumDbCosmosdbConnectionModev1250,
	ruleEnumDiskIoDirectionv1250,
	ruleEnumFaasTriggerv1250,
	ruleEnumGraphqlOperationTypev1250,
	ruleEnumIosStatev1250,
	ruleEnumJvmMemoryTypev1250,
	ruleEnumJvmThreadStatev1250,
	ruleEnumLogIostreamv1250,
	ruleEnumMessagingRocketmqConsumptionModelv1250,
	ruleEnumMessagingRocketmqMessageTypev1250,
	ruleEnumNetworkIoDirectionv1250,
	ruleEnumOpentracingRefTypev1250,
	ruleEnumOtelStatusCodev1250,
	ruleEnumStatev1250,
	ruleEnumSystemFilesystemStatev1250,
	ruleEnumSystemNetworkStatev1250,
	ruleEnumSystemPagingDirectionv1250,
	ruleEnumSystemPagingStatev1250,
	ruleEnumSystemPagingTypev1250,
}

var ruleEnumAndroidStatev1250 = &rule.AttributeRule{
	Name:         "enum.android.state",
	Title:        "This attribute represents the state the application has transitioned into at the occurrence of the event.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "android.state", []string{ "created", "background", "foreground" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumAwsEcsLaunchtypev1250 = &rule.AttributeRule{
	Name:         "enum.aws.ecs.launchtype",
	Title:        "The [launch type](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_types.html) for an ECS task.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "aws.ecs.launchtype", []string{ "ec2", "fargate" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumDbCosmosdbConnectionModev1250 = &rule.AttributeRule{
	Name:         "enum.db.cosmosdb.connection_mode",
	Title:        "Cosmos client connection mode.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "db.cosmosdb.connection_mode", []string{ "gateway", "direct" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumDiskIoDirectionv1250 = &rule.AttributeRule{
	Name:         "enum.disk.io.direction",
	Title:        "The disk IO operation direction.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "disk.io.direction", []string{ "read", "write" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumFaasTriggerv1250 = &rule.AttributeRule{
	Name:         "enum.faas.trigger",
	Title:        "Type of the trigger which caused this function invocation.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "faas.trigger", []string{ "datasource", "http", "pubsub", "timer", "other" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumGraphqlOperationTypev1250 = &rule.AttributeRule{
	Name:         "enum.graphql.operation.type",
	Title:        "The type of the operation being executed.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "graphql.operation.type", []string{ "query", "mutation", "subscription" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumIosStatev1250 = &rule.AttributeRule{
	Name:         "enum.ios.state",
	Title:        "This attribute represents the state the application has transitioned into at the occurrence of the event.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "ios.state", []string{ "active", "inactive", "background", "foreground", "terminate" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumJvmMemoryTypev1250 = &rule.AttributeRule{
	Name:         "enum.jvm.memory.type",
	Title:        "The type of memory.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "jvm.memory.type", []string{ "heap", "non_heap" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityStable,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumJvmThreadStatev1250 = &rule.AttributeRule{
	Name:         "enum.jvm.thread.state",
	Title:        "State of the thread.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "jvm.thread.state", []string{ "new", "runnable", "blocked", "waiting", "timed_waiting", "terminated" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityStable,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumLogIostreamv1250 = &rule.AttributeRule{
	Name:         "enum.log.iostream",
	Title:        "The stream associated with the log. See below for a list of well-known values.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "log.iostream", []string{ "stdout", "stderr" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumMessagingRocketmqConsumptionModelv1250 = &rule.AttributeRule{
	Name:         "enum.messaging.rocketmq.consumption_model",
	Title:        "Model of message consumption. This only applies to consumer spans.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "messaging.rocketmq.consumption_model", []string{ "clustering", "broadcasting" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumMessagingRocketmqMessageTypev1250 = &rule.AttributeRule{
	Name:         "enum.messaging.rocketmq.message.type",
	Title:        "Type of message.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "messaging.rocketmq.message.type", []string{ "normal", "fifo", "delay", "transaction" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumNetworkIoDirectionv1250 = &rule.AttributeRule{
	Name:         "enum.network.io.direction",
	Title:        "The network IO operation direction.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "network.io.direction", []string{ "transmit", "receive" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumOpentracingRefTypev1250 = &rule.AttributeRule{
	Name:         "enum.opentracing.ref_type",
	Title:        "Parent-child Reference type",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "opentracing.ref_type", []string{ "child_of", "follows_from" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumOtelStatusCodev1250 = &rule.AttributeRule{
	Name:         "enum.otel.status_code",
	Title:        "Name of the code, either OK or ERROR. MUST NOT be set if the status code is UNSET.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "otel.status_code", []string{ "OK", "ERROR" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityStable,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumStatev1250 = &rule.AttributeRule{
	Name:         "enum.state",
	Title:        "The state of a connection in the pool",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "state", []string{ "idle", "used" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumSystemFilesystemStatev1250 = &rule.AttributeRule{
	Name:         "enum.system.filesystem.state",
	Title:        "The filesystem state",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "system.filesystem.state", []string{ "used", "free", "reserved" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumSystemNetworkStatev1250 = &rule.AttributeRule{
	Name:         "enum.system.network.state",
	Title:        "A stateless protocol MUST NOT set this attribute",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "system.network.state", []string{ "close", "close_wait", "closing", "delete", "established", "fin_wait_1", "fin_wait_2", "last_ack", "listen", "syn_recv", "syn_sent", "time_wait" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumSystemPagingDirectionv1250 = &rule.AttributeRule{
	Name:         "enum.system.paging.direction",
	Title:        "The paging access direction",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "system.paging.direction", []string{ "in", "out" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumSystemPagingStatev1250 = &rule.AttributeRule{
	Name:         "enum.system.paging.state",
	Title:        "The memory paging state",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "system.paging.state", []string{ "used", "free" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

var ruleEnumSystemPagingTypev1250 = &rule.AttributeRule{
	Name:         "enum.system.paging.type",
	Title:        "The memory paging type",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "system.paging.type", []string{ "major", "minor" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
  Version:      "v1.25.0",
}

