// Code generated by otel-lint. DO NOT EDIT.
package attributes

import (
	"github.com/ymtdzzz/otel-lint/pkg/rule"
)

var RulesEnumv1240 = []*rule.AttributeRule{
	ruleEnumAndroidStatev1240,
	ruleEnumAwsEcsLaunchtypev1240,
	ruleEnumDbCosmosdbConnectionModev1240,
	ruleEnumDiskIoDirectionv1240,
	ruleEnumFaasTriggerv1240,
	ruleEnumGraphqlOperationTypev1240,
	ruleEnumIosStatev1240,
	ruleEnumJvmMemoryTypev1240,
	ruleEnumJvmThreadStatev1240,
	ruleEnumLogIostreamv1240,
	ruleEnumMessagingRocketmqConsumptionModelv1240,
	ruleEnumMessagingRocketmqMessageTypev1240,
	ruleEnumNetworkIoDirectionv1240,
	ruleEnumOpentracingRefTypev1240,
	ruleEnumOtelStatusCodev1240,
	ruleEnumStatev1240,
	ruleEnumSystemFilesystemStatev1240,
	ruleEnumSystemNetworkStatev1240,
	ruleEnumSystemPagingDirectionv1240,
	ruleEnumSystemPagingStatev1240,
	ruleEnumSystemPagingTypev1240,
}

var ruleEnumAndroidStatev1240 = &rule.AttributeRule{
	Name:         "enum.android.state",
	Title:        "This attribute represents the state the application has transitioned into at the occurrence of the event.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "android.state", []string{ "created", "background", "foreground" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumAwsEcsLaunchtypev1240 = &rule.AttributeRule{
	Name:         "enum.aws.ecs.launchtype",
	Title:        "The [launch type](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_types.html) for an ECS task.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "aws.ecs.launchtype", []string{ "ec2", "fargate" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumDbCosmosdbConnectionModev1240 = &rule.AttributeRule{
	Name:         "enum.db.cosmosdb.connection_mode",
	Title:        "Cosmos client connection mode.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "db.cosmosdb.connection_mode", []string{ "gateway", "direct" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumDiskIoDirectionv1240 = &rule.AttributeRule{
	Name:         "enum.disk.io.direction",
	Title:        "The disk IO operation direction.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "disk.io.direction", []string{ "read", "write" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumFaasTriggerv1240 = &rule.AttributeRule{
	Name:         "enum.faas.trigger",
	Title:        "Type of the trigger which caused this function invocation.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "faas.trigger", []string{ "datasource", "http", "pubsub", "timer", "other" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumGraphqlOperationTypev1240 = &rule.AttributeRule{
	Name:         "enum.graphql.operation.type",
	Title:        "The type of the operation being executed.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "graphql.operation.type", []string{ "query", "mutation", "subscription" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumIosStatev1240 = &rule.AttributeRule{
	Name:         "enum.ios.state",
	Title:        "This attribute represents the state the application has transitioned into at the occurrence of the event.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "ios.state", []string{ "active", "inactive", "background", "foreground", "terminate" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumJvmMemoryTypev1240 = &rule.AttributeRule{
	Name:         "enum.jvm.memory.type",
	Title:        "The type of memory.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "jvm.memory.type", []string{ "heap", "non_heap" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityStable,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumJvmThreadStatev1240 = &rule.AttributeRule{
	Name:         "enum.jvm.thread.state",
	Title:        "State of the thread.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "jvm.thread.state", []string{ "new", "runnable", "blocked", "waiting", "timed_waiting", "terminated" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityStable,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumLogIostreamv1240 = &rule.AttributeRule{
	Name:         "enum.log.iostream",
	Title:        "The stream associated with the log. See below for a list of well-known values.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "log.iostream", []string{ "stdout", "stderr" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumMessagingRocketmqConsumptionModelv1240 = &rule.AttributeRule{
	Name:         "enum.messaging.rocketmq.consumption_model",
	Title:        "Model of message consumption. This only applies to consumer spans.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "messaging.rocketmq.consumption_model", []string{ "clustering", "broadcasting" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumMessagingRocketmqMessageTypev1240 = &rule.AttributeRule{
	Name:         "enum.messaging.rocketmq.message.type",
	Title:        "Type of message.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "messaging.rocketmq.message.type", []string{ "normal", "fifo", "delay", "transaction" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumNetworkIoDirectionv1240 = &rule.AttributeRule{
	Name:         "enum.network.io.direction",
	Title:        "The network IO operation direction.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "network.io.direction", []string{ "transmit", "receive" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumOpentracingRefTypev1240 = &rule.AttributeRule{
	Name:         "enum.opentracing.ref_type",
	Title:        "Parent-child Reference type",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "opentracing.ref_type", []string{ "child_of", "follows_from" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumOtelStatusCodev1240 = &rule.AttributeRule{
	Name:         "enum.otel.status_code",
	Title:        "Name of the code, either OK or ERROR. MUST NOT be set if the status code is UNSET.",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "otel.status_code", []string{ "OK", "ERROR" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumStatev1240 = &rule.AttributeRule{
	Name:         "enum.state",
	Title:        "The state of a connection in the pool",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "state", []string{ "idle", "used" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumSystemFilesystemStatev1240 = &rule.AttributeRule{
	Name:         "enum.system.filesystem.state",
	Title:        "The filesystem state",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "system.filesystem.state", []string{ "used", "free", "reserved" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumSystemNetworkStatev1240 = &rule.AttributeRule{
	Name:         "enum.system.network.state",
	Title:        "A stateless protocol MUST NOT set this attribute",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "system.network.state", []string{ "close", "close_wait", "closing", "delete", "established", "fin_wait_1", "fin_wait_2", "last_ack", "listen", "syn_recv", "syn_sent", "time_wait" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumSystemPagingDirectionv1240 = &rule.AttributeRule{
	Name:         "enum.system.paging.direction",
	Title:        "The paging access direction",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "system.paging.direction", []string{ "in", "out" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumSystemPagingStatev1240 = &rule.AttributeRule{
	Name:         "enum.system.paging.state",
	Title:        "The memory paging state",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "system.paging.state", []string{ "used", "free" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

var ruleEnumSystemPagingTypev1240 = &rule.AttributeRule{
	Name:         "enum.system.paging.type",
	Title:        "The memory paging type",
	Check:        func(sa *rule.SignalAttributes) bool { return valueValidEnum(sa, "system.paging.type", []string{ "major", "minor" }) },
	Severity:     rule.SeverityError,
	Stability:    rule.StabilityExperimental,
	Source:       "",
	Version:      "v1.24.0",
}

